const products = {
    electronics: [
        { id: 1, name: "Smartphone", price: 699, brand: "Brand A" },
        { id: 2, name: "Laptop", price: 999, brand: "Brand B" },
        { id: 3, name: "Bluetooth Headphones", price: 149, brand: "Brand C" },
        { id: 4, name: "Smartwatch", price: 199, brand: "Brand D" },
        { id: 5, name: "4K TV", price: 599, brand: "Brand E" },
        { id: 6, name: "Wireless Mouse", price: 29, brand: "Brand F" },
        { id: 7, name: "Gaming Console", price: 299, brand: "Brand G" },
        { id: 8, name: "Portable Speaker", price: 79, brand: "Brand H" },
        { id: 9, name: "Tablet", price: 329, brand: "Brand I" },
        { id: 10, name: "Digital Camera", price: 450, brand: "Brand J" },
        { id: 11, name: "Power Bank", price: 39, brand: "Brand K" },
        { id: 12, name: "Smart Light Bulb", price: 15, brand: "Brand L" },
        { id: 13, name: "Laptop Bag", price: 49, brand: "Brand M" },
        { id: 14, name: "VR Headset", price: 249, brand: "Brand N" },
        { id: 15, name: "Game Controller", price: 39, brand: "Brand O" },
        { id: 16, name: "Smart Glasses", price: 299, brand: "Brand P" },

    ],
    homeAppliances: [
        { id: 1, name: "Air Conditioner", price: 350, brand: "Brand A" },
        { id: 2, name: "Refrigerator", price: 850, brand: "Brand B" },
        { id: 3, name: "Washing Machine", price: 400, brand: "Brand C" },
        { id: 4, name: "Microwave Oven", price: 120, brand: "Brand D" },
        { id: 5, name: "Electric Kettle", price: 40, brand: "Brand E" },
        { id: 6, name: "Blender", price: 60, brand: "Brand F" },
        { id: 7, name: "Coffee Maker", price: 100, brand: "Brand G" },
        { id: 8, name: "Dishwasher", price: 500, brand: "Brand H" },
        { id: 9, name: "Air Purifier", price: 180, brand: "Brand I" },
        { id: 10, name: "Vacuum Cleaner", price: 150, brand: "Brand J" },
        { id: 11, name: "Toaster", price: 35, brand: "Brand K" },
        { id: 12, name: "Dehumidifier", price: 120, brand: "Brand L" },
        { id: 13, name: "Induction Cooktop", price: 75, brand: "Brand M" },
        { id: 14, name: "Portable Heater", price: 65, brand: "Brand N" },
        { id: 15, name: "Smart Thermostat", price: 120, brand: "Brand O" },
        { id: 16, name: "Electric Fan", price: 55, brand: "Brand P" },

    ],
    clothing: [
        { id: 1, name: "T-Shirt", price: 25, brand: "Brand A" },
        { id: 2, name: "Jeans", price: 45, brand: "Brand B" },
        { id: 3, name: "Jacket", price: 60, brand: "Brand C" },
        { id: 4, name: "Sneakers", price: 80, brand: "Brand D" },
        { id: 5, name: "Sweater", price: 50, brand: "Brand E" },
        { id: 6, name: "Hoodie", price: 40, brand: "Brand F" },
        { id: 7, name: "Cap", price: 20, brand: "Brand G" },
        { id: 8, name: "Polo Shirt", price: 35, brand: "Brand H" },
        { id: 9, name: "Shorts", price: 30, brand: "Brand I" },
        { id: 10, name: "Dress", price: 65, brand: "Brand J" },
        { id: 11, name: "Suit", price: 150, brand: "Brand K" },
        { id: 12, name: "Socks", price: 10, brand: "Brand L" },
        { id: 13, name: "Scarf", price: 25, brand: "Brand M" },
        { id: 14, name: "Belt", price: 15, brand: "Brand N" },
        { id: 15, name: "Gloves", price: 18, brand: "Brand O" },
        { id: 16, name: "Track Pants", price: 40, brand: "Brand P" },

    ],
    beautyPersonalCare: [
        { id: 1, name: "Shampoo", price: 15, brand: "Brand A" },
        { id: 2, name: "Conditioner", price: 18, brand: "Brand B" },
        { id: 3, name: "Facial Cleanser", price: 10, brand: "Brand C" },
        { id: 4, name: "Toothpaste", price: 5, brand: "Brand D" },
        { id: 5, name: "Deodorant", price: 7, brand: "Brand E" },
        { id: 6, name: "Body Lotion", price: 12, brand: "Brand F" },
        { id: 7, name: "Face Cream", price: 25, brand: "Brand G" },
        { id: 8, name: "Perfume", price: 45, brand: "Brand H" },
        { id: 9, name: "Hair Serum", price: 30, brand: "Brand I" },
        { id: 10, name: "Nail Polish", price: 8, brand: "Brand J" },
        { id: 11, name: "Makeup Remover", price: 12, brand: "Brand K" },
        { id: 12, name: "Sunscreen", price: 20, brand: "Brand L" },
        { id: 13, name: "Shaving Cream", price: 10, brand: "Brand M" },
        { id: 14, name: "Lip Balm", price: 4, brand: "Brand N" },
        { id: 15, name: "Face Mask", price: 15, brand: "Brand O" },
        { id: 16, name: "Face Wash", price: 12, brand: "Brand P" },

    ],
    sportsOutdoors: [
        { id: 1, name: "Tennis Racket", price: 80, brand: "Brand A" },
        { id: 2, name: "Yoga Mat", price: 25, brand: "Brand B" },
        { id: 3, name: "Camping Tent", price: 120, brand: "Brand C" },
        { id: 4, name: "Hiking Boots", price: 65, brand: "Brand D" },
        { id: 5, name: "Football", price: 25, brand: "Brand E" },
        { id: 6, name: "Basketball", price: 30, brand: "Brand F" },
        { id: 7, name: "Cycling Helmet", price: 40, brand: "Brand G" },
        { id: 8, name: "Sleeping Bag", price: 50, brand: "Brand H" },
        { id: 9, name: "Fishing Rod", price: 60, brand: "Brand I" },
        { id: 10, name: "Skateboard", price: 45, brand: "Brand J" },
        { id: 11, name: "Football Shoes", price: 70, brand: "Brand K" },
        { id: 12, name: "Climbing Rope", price: 80, brand: "Brand L" },
        { id: 13, name: "Kettlebell", price: 35, brand: "Brand M" },
        { id: 14, name: "Yoga Blocks", price: 15, brand: "Brand N" },
        { id: 15, name: "Swimming Goggles", price: 10, brand: "Brand O" },
        { id: 16, name: "Baseball Glove", price: 50, brand: "Brand P" },

    ],
    furniture: [
        { id: 1, name: "Sofa", price: 800, brand: "Brand A" },
        { id: 2, name: "Dining Table", price: 500, brand: "Brand B" },
        { id: 3, name: "Coffee Table", price: 150, brand: "Brand C" },
        { id: 4, name: "Bookshelf", price: 100, brand: "Brand D" },
        { id: 5, name: "Bed Frame", price: 350, brand: "Brand E" },
        { id: 6, name: "Office Chair", price: 150, brand: "Brand F" },
        { id: 7, name: "Wardrobe", price: 450, brand: "Brand G" },
        { id: 8, name: "Side Table", price: 80, brand: "Brand H" },
        { id: 9, name: "TV Stand", price: 200, brand: "Brand I" },
        { id: 10, name: "Recliner", price: 400, brand: "Brand J" },
        { id: 11, name: "Dresser", price: 250, brand: "Brand K" },
        { id: 12, name: "Bean Bag", price: 70, brand: "Brand L" },
        { id: 13, name: "Kitchen Island", price: 300, brand: "Brand M" },
        { id: 14, name: "Bar Stool", price: 60, brand: "Brand N" },
        { id: 15, name: "Console Table", price: 120, brand: "Brand O" },
        { id: 16, name: "Coffee Mug Set", price: 30, brand: "Brand P" },

    ]
};

export default products;
